els-ASAP auto commit file/tag tuned-2.11.0-5.el7.src.rpm

diff --git a/src/profiles/functions b/src/profiles/functions
--- a/src/profiles/functions
+++ b/src/profiles/functions
@@ -503,26 +503,29 @@ eee_set_normal_fsb() {
 
 kvm_modprobe_file=/etc/modprobe.d/kvm.rt.tuned.conf
 
-setup_kvm_mod_low_latency()
-{
-	if [ -f $kvm_modprobe_file ]; then
-		return
-	fi
-
-	modinfo -p kvm | grep -q kvmclock_periodic_sync
-	if [ "$?" -eq 0 ]; then
-		echo "options kvm kvmclock_periodic_sync=0" > $kvm_modprobe_file
-	fi
-
-	modinfo -p kvm_intel | grep -q ple_gap
-	if [ "$?" -eq 0 ]; then
-		echo "options kvm_intel ple_gap=0" >> $kvm_modprobe_file
-	fi
-}
-
 teardown_kvm_mod_low_latency()
 {
 	rm -f $kvm_modprobe_file
+}
+
+setup_kvm_mod_low_latency()
+{
+	local HAS_KPS=""
+	local HAS_PLE_GAP=""
+	local WANTS_KPS=""
+	local WANTS_PLE_GAP=""
+
+	modinfo -p kvm | grep -q kvmclock_periodic_sync && HAS_KPS=1
+	modinfo -p kvm_intel | grep -q ple_gap && HAS_PLE_GAP=1
+	grep -qs kvmclock_periodic_sync "$kvm_modprobe_file" && WANTS_KPS=1
+	grep -qs ple_gap "$kvm_modprobe_file" && WANTS_PLE_GAP=1
+
+	if [ "$HAS_KPS" != "$WANTS_KPS" -o "$HAS_PLE_GAP" != "$WANTS_PLE_GAP" ]; then
+		teardown_kvm_mod_low_latency
+		[ "$HAS_KPS" ] && echo "options kvm kvmclock_periodic_sync=0" > $kvm_modprobe_file
+		[ "$HAS_PLE_GAP" ] && echo "options kvm_intel ple_gap=0" >> $kvm_modprobe_file
+	fi
+	return 0
 }
 
 #
@@ -531,35 +534,30 @@ teardown_kvm_mod_low_latency()
 
 KSM_SERVICES="ksm ksmtuned"
 KSM_RUN_PATH=/sys/kernel/mm/ksm/run
+KSM_MASK_FILE="${STORAGE_PERSISTENT}/ksm-masked"
 
 disable_ksm()
 {
-	for s in $KSM_SERVICES; do
-		if systemctl is-enabled -q $s; then
-			systemctl -q disable $s
+	if [ ! -f $KSM_MASK_FILE ]; then
+		# Always create $KSM_MASK_FILE, since we don't want to
+		# run any systemctl commands during boot
+		if ! touch $KSM_MASK_FILE; then
+			die "failed to create $KSM_MASK_FILE"
 		fi
-
-		if systemctl is-active -q $s; then
-			systemctl -q stop $s
-		fi
-	done
-
-	if [ -f $KSM_RUN_PATH ]; then
+		systemctl --now --quiet mask $KSM_SERVICES
 		# Unmerge all shared pages
-		echo 2 > $KSM_RUN_PATH
+		test -f $KSM_RUN_PATH && echo 2 > $KSM_RUN_PATH
 	fi
 }
 
+# Should only be called when full_rollback == true
 enable_ksm()
 {
-	for s in $KSM_SERVICES; do
-		systemctl -q preset $s
-
-		# Only start the service if it's enabled by defaut
-		if systemctl is-enabled -q $s; then
-			systemctl start $s
+	if [ -f $KSM_MASK_FILE ]; then
+		if systemctl --quiet unmask $KSM_SERVICES; then
+			rm -f $KSM_MASK_FILE
 		fi
-	done
+	fi
 }
 
 die() {
